### PR TITLE
Minor proposals

### PR DESCRIPTION
**Pull request by nulltoken**
- Add a link to the NuGet package in the README
 - Update NuGet dependencies

### CODE REVIEW

**Comment by nulltoken** [comment]
Wow! I think the Travis **[build log](https://travis-ci.org/ethomson/infinity.net/builds/83586043)** is really worth a shot :roller_coaster: /cc @Therzok

I'm slightly puzzled by the AppVeyor issue.. Any idea?

**Comment by nulltoken** [comment]
OK. Everything seems to be tamed now

**Comment by ethomson** [comment]
Neat!  Thanks!

**Comment by Therzok** [comment]
The travis bot is using a really _old_ mono version (3.12). I guess that shouldn't happen with a newer one (not entirely sure though).

Without a solid repro or a test case, I'm not sure how to get this fixed.

The [constructor](https://github.com/mono/mono/blob/master/mcs/class/Mono.Security/Mono.Security.X509/X509Certificate.cs#L219) does do a null check before, so it's probably a crash in the clone implementation.

Not sure if opening a bug against 3.12 is valid tho.

**Comment by Therzok** [comment]
https://bugzilla.xamarin.com/show_bug.cgi?id=34550

**Pull request merged**
